name: Rust

on:
  push:
    branches: [ "master", "2.0" ]
  pull_request:
    branches: [ "master", "2.0" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo check
        run: cargo check --benches --tests --all-features
      - name: Run cargo clippy
        run: cargo clippy --benches --tests --all-features -- -D warnings -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used --no-deps
      - name: Run cargo fmt
        run: cargo fmt --check
      - name: Run cargo doc
        run: cargo doc --all-features --no-deps
        env:
            RUSTDOCFLAGS: --cfg docsrs
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cargo test
        run: cargo test --all-features
        env:
            RUSTDOCFLAGS: --cfg docsrs
  msrv:
    name: MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install MSRV
        uses: dtolnay/rust-toolchain@master
        with:
            toolchain: "1.89"
            components: rustfmt, clippy
      - name: Check MSRV compatibility
        run: cargo check --all-features
